"""Add cascade delete to therapist appointments

Revision ID: 1f8b67ce6101
Revises: 327e6b0587b1
Create Date: 2026-04-21 03:55:11.893165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8b67ce6101'
down_revision: Union[str, None] = '327e6b0587b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
