"""Add new atribute users to docuemnt number.

Revision ID: 327e6b0587b1
Revises: 2e654ab59e2c
Create Date: 2026-04-07 03:32:54.346634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327e6b0587b1'
down_revision: Union[str, None] = '2e654ab59e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('document_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'patients', ['document_number'])
    op.add_column('therapists', sa.Column('document_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'therapists', ['document_number'])
    op.add_column('users', sa.Column('document_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['document_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'document_number')
    op.drop_constraint(None, 'therapists', type_='unique')
    op.drop_column('therapists', 'document_number')
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'document_number')
    # ### end Alembic commands ###
